### PR TITLE
Add Linux VMware Workstation setup script

### PR DESCRIPTION
**Pull request by AlainODea**

### CODE REVIEW

**Comment by AlainODea** [comment]
Tested to work on Ubuntu 14.04.

**Comment by AlainODea** [comment]
Allows ssh to headnode, but not access to Operations Portal.  Likely a permissions issue with /dev/vmnet*.  I'm closing this for now until I verify that is fixed.

**Comment by AlainODea** [comment]
Fixed the issue.  I wasn't handling the case where the **vmnetadm** group might already exist.

**Comment by trentm** [comment]
Merged. Thanks, Alain!

**Comment by AlainODea** [comment]
My pleasure Trent :)

**Pull request merged**
